// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_y5mHL1L_GUTkPdSnL7AFj9vYUo3LIKc',
    appId: '1:582818276388:web:f9a66aab1dbb82e7e9a4b1',
    messagingSenderId: '582818276388',
    projectId: 'sema-mama-f365d',
    authDomain: 'sema-mama-f365d.firebaseapp.com',
    databaseURL: 'https://sema-mama-f365d-default-rtdb.firebaseio.com',
    storageBucket: 'sema-mama-f365d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXs0c2eWALZRIftqgqXt4wW_CMPEPxef4',
    appId: '1:582818276388:android:11ded31a414dfe0ae9a4b1',
    messagingSenderId: '582818276388',
    projectId: 'sema-mama-f365d',
    databaseURL: 'https://sema-mama-f365d-default-rtdb.firebaseio.com',
    storageBucket: 'sema-mama-f365d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB76c_SmzEaMoKX9X-QaTt7egs3EGc-Cxw',
    appId: '1:582818276388:ios:664de97b5fd572ece9a4b1',
    messagingSenderId: '582818276388',
    projectId: 'sema-mama-f365d',
    databaseURL: 'https://sema-mama-f365d-default-rtdb.firebaseio.com',
    storageBucket: 'sema-mama-f365d.appspot.com',
    androidClientId: '582818276388-ki6nmat714l6gfmpaqti8lb1pr8gu8d2.apps.googleusercontent.com',
    iosClientId: '582818276388-of568iahp7hq2l9d1v2tcg5l1a9of7ng.apps.googleusercontent.com',
    iosBundleId: 'com.example.semmaMaam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB76c_SmzEaMoKX9X-QaTt7egs3EGc-Cxw',
    appId: '1:582818276388:ios:9cd80ec1cbba1697e9a4b1',
    messagingSenderId: '582818276388',
    projectId: 'sema-mama-f365d',
    databaseURL: 'https://sema-mama-f365d-default-rtdb.firebaseio.com',
    storageBucket: 'sema-mama-f365d.appspot.com',
    androidClientId: '582818276388-ki6nmat714l6gfmpaqti8lb1pr8gu8d2.apps.googleusercontent.com',
    iosClientId: '582818276388-iu7cqtba2m68sv0lcq82r1ubeu39qr69.apps.googleusercontent.com',
    iosBundleId: 'com.example.semmaMaam.RunnerTests',
  );
}
